### ISSUE TITLE
Webcam discovery timeout

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/vid#18]
We had a user report a timeout exception with the vid extension in NetLogo 6.0.4.  Searching the issues, I saw this had been [reported before](https://github.com/NetLogo/NetLogo/issues/1240) and the timeout was increased to 1.5 seconds from 0.5 seconds in response.

I think it might be worth increasing the timeout up to ~15 seconds, and definitely handling the exception in a better way.  If possible, alerting the user of the timeout and giving the option to wait a longer period of time.  

```
java.util.concurrent.TimeoutException: Webcams discovery timeout (1500
ms) has been exceeded
 at
com.github.sarxos.webcam.WebcamDiscoveryService.getWebcams(WebcamDiscoveryService.java:128)
 at com.github.sarxos.webcam.Webcam.getWebcams(Webcam.java:874)
 at
org.nlogo.extensions.vid.Camera$.$anonfun$cameraNames$1(Camera.scala:40)
 at
org.nlogo.extensions.vid.Camera$.withContextClassLoader(Camera.scala:33)
 at org.nlogo.extensions.vid.Camera$.cameraNames(Camera.scala:40)
 at org.nlogo.extensions.vid.CameraSelect.perform(CameraSelect.scala:10)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 at org.nlogo.nvm.Context.runExclusive(Context.java:133)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
 at org.nlogo.prim._asm_buttonselectcamera_carefully_0.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at scala.util.control.Exception$Catch.apply(Exception.scala:224)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_172 (Oracle Corporation;
1.8.0_172-b11)
operating system: Windows 7 6.1 (amd64 processor)
Scala version 2.12.4
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Video Camera Example

10:49:17.269 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
10:49:17.196 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget)
AWT-EventQueue-0
10:49:17.101 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1
(org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:49:16.901 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1
(org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:49:16.701 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1
(org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:49:16.501 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1
(org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:49:16.301 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1
(org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:49:16.101 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1
(org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:49:15.901 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1
(org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:49:15.701 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1
(org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

**Comment by LaCuneta** [comment]
The timeout has been removed with the JavaCV updates.
